### ISSUE TITLE
What basis is used for Color Index? Discrepancy on Betelgeuse

### ISSUE THREAD

**Issue by connorjak** [astronexus/HYG-Database#26]
Betelgeuse (https://simbad.u-strasbg.fr/simbad/sim-id?Ident=HD+39801) has a B-V color index of 1.85 according to the databases SIMBAD references. In the HYG v3 database, this color index is 1.5.

Is this a one-off error? Is it a matter of different bands being used for B and/or V?

**Comment by astronexus** [comment]
The color indices are generally the HIPPARCOS values for the B-V color index. The value for Betelgeuse is 1.500 as in the following results directly from HIPPARCOS: https://hipparcos-tools.cosmos.esa.int/cgi-bin/HIPcatalogueSearch.pl?hipId=27989&hdId=&tyc1=&tyc2=&tyc3= . 

Having said that, since Betelgeuse is intrinsically quite variable, its B-V color index also varies quite a bit. Here's an example of a fairly sizable fluctuation during its deep minimum in 2019-2020: https://astronomy.stackexchange.com/questions/35095/color-index-b-v-of-the-dimming-betelgeuse

So ... not really sure this is an actual error - any chosen value of B-V for a star like Betelgeuse is likely only valid for the specific time of observation (or is possibly an averaged value over a long time) and should be treated as a rough estimate only.
