### ISSUE TITLE
The star catalog AT-HYG lacks proper motion data. Will subsequent versions supplement this information?

### ISSUE THREAD

**Issue by lcx366** [astronexus/HYG-Database#28]

**Comment by astronexus** [comment]
This is on the radar, but I don't have a definite time frame for when I will add it. The general list of changes I envision for the next few releases is:

1. Add proper motion data from GAIA.
2. Add radial velocity values (and so also full 3D space velocities) from GAIA.
3. Add BT (blue) magnitudes to Tycho's VT, giving us color index (on the BT and VT values) and also possibly an estimate of V magnitudes for Tycho stars, making magnitude values more consistent.
4. Add spectral types directly from HD stars to ones that don't have them in HIP.
5. Add 3-letter constellation labels for non-HYG entries.

I am likely to focus on 3-5 first since they involve less intensive data processing.

**Comment by astronexus** [comment]
AT-HYG v2.0 has proper motion and radial velocity data from Gaia DR3 for most stars. Proper motions are essentially complete; RVs are about 90% complete, with HYG filling in a number of the gaps.
