### ISSUE TITLE
Truncated constellation values?

### ISSUE THREAD

**Issue by Sweater-Baron** [astronexus/HYG-Database#3]
Stars with IDs 46504 and 115766 have their constellation listed as 'A', and the constellation for star 46501 is listed as "B". Are these just non-standard constellation abbreviations that I'm not aware of, or are they errors that should be corrected? (I'm not an astronomy guy, so forgive me if this is a stupid question.)

**Comment by astronexus** [comment]
Confirm you have the most recent version of the data set.  A few months ago I found a few incorrect constellation values in the last revision and changed them to the correct values.  In the current set, star ID 46504 has the constellation Leo and 115766 has the constellation Peg (Pegasus).

**Comment by Sweater-Baron** [comment]
I just checked, and I'm using the latest version of hygdata_v3.csv file from astronexus.com, which I guess is an older version than the one here on GitHub.

More precise versions in the filenames might be useful for presenting this kind of mixup. Maybe you could rename the current version to hygdata_v3.1?

**Comment by retroj** [comment]
2 cents to throw in - I'm not in favor of including the version in the filename because if every little change and correction involves renaming the database files, we lose benefits of version control, and software using these files has to be a little more complex to account for unpredictable filenames.  If software needs to be able to know version information about the database, an easily parseable auxiliary file (called "VERSION" or such) would be more appropriate.
