### ISSUE TITLE
Missing distance for named stars

### ISSUE THREAD

**Issue by chrleon** [astronexus/HYG-Database#30]
![image](https://github.com/astronexus/HYG-Database/assets/347919/e04074ab-dd6c-4de6-aa3d-2b8e76679581)
3C 273 and Polis has missing dist data.

**Comment by chrleon** [comment]
proper	id	dist
3C 273	1272569	
Polis	1831728

**Comment by astronexus** [comment]
In general, when distances were unknown or of poor quality (negative parallax or parallax indistinguishable from 0 based on typical measurement error), the distance was omitted. These two entries are a good example of the situation.

3C 273 is a quasar, too far away to have reliable distance data in Gaia or any of the HYG sources. Its distance is actually known reasonably precisely, but since it is not a star and its actual distance is so much larger than any other object in this catalog, it didn't make sense to make a special case out of it. In any event the distance can't be obtained from the data sources used for other objects in HYG or in AT-HYG.

Polis is Mu Sgr, which does not have an accurate distance in the data sources I used (HIPPARCOS has a parallax of 0.09 mas, far below the measurement uncertainty, so it is not included in HYG; Gaia DR3 does not contain this star, so it was not included in AT-HYG's distance data either).
