### ISSUE TITLE
Cluster of Stars at Same Distance

### ISSUE THREAD

**Issue by bbernicker** [astronexus/HYG-Database#9]
So I have been using this data for a project and plotted the distances in parsecs. When I filter the data, 91.46% of the stars are fewer than 991 parsecs away, zero stars are between 991 and 99999 parsecs away, and then the remaining 10,215 stars (8.54%) are all between 99999.25 and 100000.25 parsecs away (within one parsec). Is there a reason why this dataset includes so many stars that are almost exactly one hundred thousand parsecs away and none between one thousand and one-hundred thousand parsecs?

**Comment by brandon-rhodes** [comment]
Since no one has written an official answer for you, I will make a quick guess: I would assume that the reason is that the telescope resolution available when the survey was made could not reliably detect  the distance to stars more than ~990 parsecs away, and so stars farther away than that were put “at infinity” way out at the arbitrarily large distance of 100k parsecs. Since the galaxy is only about 30k parsecs across, maybe a value of “100k parsecs away” is unlikely to be confused with a real-life distance to a particular star?

**Comment by astronexus** [comment]
This is essentially correct.

The oldest version of the database used 100,000 as a placeholder value for "distance not known" or "distance considered unreliable". I am considering revising the DB to replace these values with true NULLs instead.

**Comment by bbernicker** [comment]
That makes sense. I'm guessing the XYZ coordinates are just calculated from this arbitrary value then?
